### ISSUE TITLE
Tests failure

### ISSUE THREAD

**Issue by etataurov** [apatrushev/ServerAccess#59]
```
java.lang.AssertionError: 
Expected: a collection containing "source=file:///var/folders/9q/m53br8dx3fd5gyhwchcxv98m0000gn/T/junit7101532984635018458/junit1415633578958550902/accounts.xml"
     but: was "# You can define several sources, with different number each", was "source=file:///private/var/folders/9q/m53br8dx3fd5gyhwchcxv98m0000gn/T/junit7101532984635018458/junit1415633578958550902/accounts.xml", was "#source1=<some another source file or url here>", was "", was "# Use 'browser' variable to set custom web browser", was "#browser=xdg-open  {url}", was "#browser=open  {url}", was "#browser=cmd  /C  start {url}", was "#browser=cmd  /C  @start {url}", was "", was "# Use 'ftp' variable to set custom FTP browser", was "#ftp=gftp  ftp://anonymous@{host}:{port}", was "#ftp=putty  {options}  -telnet  {host}  -P  {port}", was "#ftp=open  ftp://anonymous@{host}:{port}", was "", was "# Use 'terminal' variable to set custom terminal launcher.", was "# Seek for more documentation on http://github.com/apatrushev/ServerAccess", was "#terminal=xterm  {options}  -e  telnet {host} {port}", was "#terminal=putty  {options}  -telnet  {host}  -P  {port}", was "#terminal=open  telnet://{host}:{port}"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at ru.naumen.servacc.test.settings.impl.DefaultConfigurationTest.defaultPropertiesFileMustContainALinkToDefaultAccountFile(DefaultConfigurationTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

```
➜  ServerAccess git:(master) gradle -v                 

------------------------------------------------------------
Gradle 2.4
------------------------------------------------------------

Build time:   2015-05-05 08:09:24 UTC
Build number: none
Revision:     5c9c3bc20ca1c281ac7972643f1e2d190f2c943c

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.4 compiled on April 29 2014
JVM:          1.7.0_45 (Oracle Corporation 24.45-b08)
OS:           Mac OS X 10.10.4 x86_64
```

**Comment by ahitrin** [comment]
Just with better formatting:

```
Expected: a collection containing "source=file:///var/folders/9q/m53br8dx3fd5gyhwchcxv98m0000gn/T/junit7101532984635018458/junit1415633578958550902/accounts.xml"
     but: was "# You can define several sources, with different number each",
          was "source=file:///private/var/folders/9q/m53br8dx3fd5gyhwchcxv98m0000gn/T/junit7101532984635018458/junit1415633578958550902/accounts.xml",
          was "#source1=<some another source file or url here>",
          was "",
          was "# Use 'browser' variable to set custom web browser",
          was "#browser=xdg-open  {url}",
          was "#browser=open  {url}",
          was "#browser=cmd  /C  start {url}",
          was "#browser=cmd  /C  @start {url}",
          was "",
          was "# Use 'ftp' variable to set custom FTP browser",
          was "#ftp=gftp  ftp://anonymous@{host}:{port}",
          was "#ftp=putty  {options}  -telnet  {host}  -P  {port}",
          was "#ftp=open  ftp://anonymous@{host}:{port}",
          was "",
          was "# Use 'terminal' variable to set custom terminal launcher.",
          was "# Seek for more documentation on http://github.com/apatrushev/ServerAccess",
          was "#terminal=xterm  {options}  -e  telnet {host} {port}",
          was "#terminal=putty  {options}  -telnet  {host}  -P  {port}",
          was "#terminal=open  telnet://{host}:{port}"
```

**Comment by ahitrin** [comment]
@etataurov please try to run build from `fix-macosx-build` branch. Does test still fail?
